CREATE TABLE IF NOT EXISTS users (
  id INTEGER UNIQUE PRIMARY KEY AUTOINCREMENT NOT NULL,
  email TEXT NOT NULL,
  password TEXT NOT NULL
);

CREATE TABLE IF NOT EXISTS tokens (
  token TEXT UNIQUE NOT NULL,
  user INTEGER REFERENCES users(id) NOT NULL,
  scope TEXT NOT NULL DEFAULT ''
);